import { writeFileSync, mkdirSync, existsSync } from "node:fs";
import { join } from "node:path";
import type { HarnessConfig } from "../config.js";
import { getPackageRoot } from "../config.js";

export interface FixtureSpec {
  name: string;
  description: string;
  input: Record<string, unknown>;
  expected: Record<string, unknown>;
  symbolName: string;
}

/** Optional: emit Rust test stubs under tools/port-harness/generated/ (not the main crate). */
export function generateRustTestScaffold(
  _config: HarnessConfig,
  fixtures: FixtureSpec[],
  moduleName: string,
): string {
  const testDir = join(getPackageRoot(), "generated", "rust_tests");
  if (!existsSync(testDir)) {
    mkdirSync(testDir, { recursive: true });
  }

  const fileName = `${moduleName}.rs`;
  const filePath = join(testDir, fileName);

  const testCases = fixtures
    .map(
      (f) => `
#[test]
#[ignore = "port-harness generated — enable after Rust port lands"]
fn ${sanitizeTestName(f.name)}() {
    // ${f.description}
    // Symbol: ${f.symbolName}
    let _input = ${jsonToRust(f.input)};
    let _expected = ${jsonToRust(f.expected)};
}
`,
    )
    .join("\n");

  const content = `//! Auto-generated by port-harness (reference only — not wired into cargo test)
//! Module: ${moduleName}

${testCases}
`;

  writeFileSync(filePath, content);
  return filePath;
}

function sanitizeTestName(name: string): string {
  return name.replace(/[^a-zA-Z0-9_]/g, "_").replace(/^(\d)/, "_$1");
}

function jsonToRust(obj: Record<string, unknown>): string {
  const entries = Object.entries(obj)
    .map(([k, v]) => `${k}: ${valueToRust(v)}`)
    .join(", ");
  if (entries.length === 0) return "()";
  return `{ ${entries} }`;
}

function valueToRust(v: unknown): string {
  if (v === null || v === undefined) return "None";
  if (typeof v === "boolean") return v ? "true" : "false";
  if (typeof v === "number") return String(v);
  if (typeof v === "string") return `"${v.replace(/"/g, '\\"')}"`;
  if (Array.isArray(v)) return `vec![${v.map(valueToRust).join(", ")}]`;
  if (typeof v === "object") return jsonToRust(v as Record<string, unknown>);
  return "/* unknown */".toString();
}
