pub const RACE_HUMAN: u8 = 1;
pub const RACE_ORC: u8 = 2;
pub const RACE_DWARF: u8 = 3;
pub const RACE_NIGHTELF: u8 = 4;
pub const RACE_UNDEAD: u8 = 5;
pub const RACE_TAUREN: u8 = 6;
pub const RACE_GNOME: u8 = 7;
pub const RACE_TROLL: u8 = 8;

pub const GENDER_MALE: u8 = 0;
pub const GENDER_FEMALE: u8 = 1;

pub const FACTION_TEMPLATE_HUMAN: u32 = 1;
pub const FACTION_TEMPLATE_ORC: u32 = 2;
pub const FACTION_TEMPLATE_DWARF: u32 = 3;
pub const FACTION_TEMPLATE_NIGHT_ELF: u32 = 4;
pub const FACTION_TEMPLATE_UNDEAD: u32 = 5;
pub const FACTION_TEMPLATE_TAUREN: u32 = 6;
pub const FACTION_TEMPLATE_GNOME: u32 = 115;
pub const FACTION_TEMPLATE_TROLL: u32 = 116;

pub const DISPLAY_ID_HUMAN_MALE: u32 = 49;
pub const DISPLAY_ID_HUMAN_FEMALE: u32 = 50;
pub const DISPLAY_ID_ORC_MALE: u32 = 51;
pub const DISPLAY_ID_ORC_FEMALE: u32 = 52;
pub const DISPLAY_ID_DWARF_MALE: u32 = 53;
pub const DISPLAY_ID_DWARF_FEMALE: u32 = 54;
pub const DISPLAY_ID_NIGHTELF_MALE: u32 = 55;
pub const DISPLAY_ID_NIGHTELF_FEMALE: u32 = 56;
pub const DISPLAY_ID_UNDEAD_MALE: u32 = 57;
pub const DISPLAY_ID_UNDEAD_FEMALE: u32 = 58;
pub const DISPLAY_ID_TAUREN_MALE: u32 = 59;
pub const DISPLAY_ID_TAUREN_FEMALE: u32 = 60;
pub const DISPLAY_ID_GNOME_MALE: u32 = 1563;
pub const DISPLAY_ID_GNOME_FEMALE: u32 = 1564;
pub const DISPLAY_ID_TROLL_MALE: u32 = 1478;
pub const DISPLAY_ID_TROLL_FEMALE: u32 = 1479;

pub fn get_player_display_id(race: u8, gender: u8) -> u32 {
    match (race, gender) {
        (RACE_HUMAN, GENDER_MALE) => DISPLAY_ID_HUMAN_MALE,
        (RACE_HUMAN, GENDER_FEMALE) => DISPLAY_ID_HUMAN_FEMALE,
        (RACE_ORC, GENDER_MALE) => DISPLAY_ID_ORC_MALE,
        (RACE_ORC, GENDER_FEMALE) => DISPLAY_ID_ORC_FEMALE,
        (RACE_DWARF, GENDER_MALE) => DISPLAY_ID_DWARF_MALE,
        (RACE_DWARF, GENDER_FEMALE) => DISPLAY_ID_DWARF_FEMALE,
        (RACE_NIGHTELF, GENDER_MALE) => DISPLAY_ID_NIGHTELF_MALE,
        (RACE_NIGHTELF, GENDER_FEMALE) => DISPLAY_ID_NIGHTELF_FEMALE,
        (RACE_UNDEAD, GENDER_MALE) => DISPLAY_ID_UNDEAD_MALE,
        (RACE_UNDEAD, GENDER_FEMALE) => DISPLAY_ID_UNDEAD_FEMALE,
        (RACE_TAUREN, GENDER_MALE) => DISPLAY_ID_TAUREN_MALE,
        (RACE_TAUREN, GENDER_FEMALE) => DISPLAY_ID_TAUREN_FEMALE,
        (RACE_GNOME, GENDER_MALE) => DISPLAY_ID_GNOME_MALE,
        (RACE_GNOME, GENDER_FEMALE) => DISPLAY_ID_GNOME_FEMALE,
        (RACE_TROLL, GENDER_MALE) => DISPLAY_ID_TROLL_MALE,
        (RACE_TROLL, GENDER_FEMALE) => DISPLAY_ID_TROLL_FEMALE,
        _ => DISPLAY_ID_HUMAN_MALE,
    }
}

pub fn get_faction_for_race(race: u8) -> u32 {
    match race {
        RACE_HUMAN => FACTION_TEMPLATE_HUMAN,
        RACE_ORC => FACTION_TEMPLATE_ORC,
        RACE_DWARF => FACTION_TEMPLATE_DWARF,
        RACE_NIGHTELF => FACTION_TEMPLATE_NIGHT_ELF,
        RACE_UNDEAD => FACTION_TEMPLATE_UNDEAD,
        RACE_TAUREN => FACTION_TEMPLATE_TAUREN,
        RACE_GNOME => FACTION_TEMPLATE_GNOME,
        RACE_TROLL => FACTION_TEMPLATE_TROLL,
        _ => FACTION_TEMPLATE_HUMAN,
    }
}
