-- PostgreSQL migration: auth / initial_schema
-- Fresh canonical auth schema. This migration intentionally does not import MySQL data.

CREATE TABLE account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY CHECK (id >= 0),
    username VARCHAR(32) NOT NULL UNIQUE,
    gmlevel SMALLINT NOT NULL DEFAULT 0 CHECK (gmlevel >= 0),
    sessionkey TEXT, v TEXT, s TEXT,
    reg_mail VARCHAR(255) NOT NULL DEFAULT '', token_key VARCHAR(100) NOT NULL DEFAULT '',
    email TEXT, joindate TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_ip VARCHAR(45) NOT NULL DEFAULT '0.0.0.0',
    last_attempt_ip VARCHAR(45) NOT NULL DEFAULT '127.0.0.1',
    last_local_ip VARCHAR(45) NOT NULL DEFAULT '127.0.0.1',
    failed_logins BIGINT NOT NULL DEFAULT 0 CHECK (failed_logins >= 0),
    locked SMALLINT NOT NULL DEFAULT 0 CHECK (locked >= 0), lock_country VARCHAR(2) NOT NULL DEFAULT '00',
    last_login TIMESTAMPTZ NOT NULL DEFAULT '1970-01-01 00:00:01+00',
    last_pwd_reset TIMESTAMPTZ NOT NULL DEFAULT '1970-01-01 00:00:01+00',
    online SMALLINT NOT NULL DEFAULT 0 CHECK (online >= 0), expansion SMALLINT NOT NULL DEFAULT 0 CHECK (expansion >= 0),
    mutetime BIGINT NOT NULL DEFAULT 0, mutereason VARCHAR(255) NOT NULL DEFAULT '', muteby VARCHAR(50) NOT NULL DEFAULT '',
    locale SMALLINT NOT NULL DEFAULT 0 CHECK (locale >= 0), os VARCHAR(4) NOT NULL DEFAULT '', platform VARCHAR(4) NOT NULL DEFAULT '',
    recruiter INTEGER NOT NULL DEFAULT 0, current_realm SMALLINT NOT NULL DEFAULT 0 CHECK (current_realm >= 0),
    banned SMALLINT NOT NULL DEFAULT 0 CHECK (banned >= 0), mail_verif SMALLINT NOT NULL DEFAULT 0 CHECK (mail_verif >= 0),
    remember_token VARCHAR(100) NOT NULL DEFAULT '', flags BIGINT NOT NULL DEFAULT 0 CHECK (flags >= 0),
    security VARCHAR(255), pass_verif VARCHAR(255), email_verif BOOLEAN NOT NULL DEFAULT FALSE, email_check VARCHAR(255),
    nostalrius_token VARCHAR(255), nostalrius_token_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    nostalrius_email TEXT, nostalrius_reason TEXT, geolock_pin INTEGER DEFAULT 0, totp_secret VARCHAR(255),
    bnet_srp_version SMALLINT NOT NULL DEFAULT 2 CHECK (bnet_srp_version >= 0),
    bnet_salt VARCHAR(64), bnet_verifier VARCHAR(512), bnet_login_ticket VARCHAR(64),
    bnet_login_ticket_expiry BIGINT NOT NULL DEFAULT 0
);
CREATE INDEX idx_account_gmlevel ON account (gmlevel);
CREATE INDEX idx_account_bnet_login_ticket ON account (bnet_login_ticket);

CREATE TABLE account_access (
    id BIGINT NOT NULL CHECK (id >= 0), gmlevel SMALLINT NOT NULL CHECK (gmlevel >= 0),
    "RealmID" INTEGER NOT NULL, PRIMARY KEY (id, "RealmID")
);
CREATE TABLE account_banned (
    banid BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
    id BIGINT NOT NULL DEFAULT 0 CHECK (id >= 0), bandate BIGINT NOT NULL DEFAULT 0,
    unbandate BIGINT NOT NULL DEFAULT 0, bannedby VARCHAR(50) NOT NULL, banreason VARCHAR(255) NOT NULL,
    active SMALLINT NOT NULL DEFAULT 1, realm SMALLINT NOT NULL DEFAULT 1, gmlevel SMALLINT NOT NULL DEFAULT 0 CHECK (gmlevel >= 0),
    PRIMARY KEY (id, bandate)
);
CREATE TABLE ip_banned (
    ip VARCHAR(45) PRIMARY KEY DEFAULT '0.0.0.0', bandate BIGINT NOT NULL, unbandate BIGINT NOT NULL,
    bannedby VARCHAR(50) NOT NULL DEFAULT '[Console]', banreason VARCHAR(255) NOT NULL DEFAULT 'no reason'
);
CREATE TABLE realmlist (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY CHECK (id >= 0), name VARCHAR(32) NOT NULL DEFAULT '' UNIQUE,
    address VARCHAR(45) NOT NULL DEFAULT '127.0.0.1', "localAddress" VARCHAR(255) NOT NULL DEFAULT '127.0.0.1',
    "localSubnetMask" VARCHAR(255) NOT NULL DEFAULT '255.255.255.0', port INTEGER NOT NULL DEFAULT 8085,
    icon SMALLINT NOT NULL DEFAULT 0 CHECK (icon >= 0), realmflags SMALLINT NOT NULL DEFAULT 2 CHECK (realmflags >= 0),
    timezone SMALLINT NOT NULL DEFAULT 0 CHECK (timezone >= 0), "allowedSecurityLevel" SMALLINT NOT NULL DEFAULT 0 CHECK ("allowedSecurityLevel" >= 0),
    population REAL NOT NULL DEFAULT 0, gamebuild_min BIGINT NOT NULL DEFAULT 0 CHECK (gamebuild_min >= 0),
    gamebuild_max BIGINT NOT NULL DEFAULT 0 CHECK (gamebuild_max >= 0), flag SMALLINT NOT NULL DEFAULT 2 CHECK (flag >= 0),
    realmbuilds VARCHAR(64) NOT NULL DEFAULT '', last_seen TIMESTAMPTZ
);
INSERT INTO realmlist (id, name, address, "localAddress", "localSubnetMask", port, icon, realmflags, timezone, "allowedSecurityLevel", population, gamebuild_min, gamebuild_max, flag, realmbuilds)
VALUES (1, 'oxcore', '127.0.0.1', '127.0.0.1', '255.255.255.0', 8085, 0, 0, 0, 0, 0, 0, 0, 2, '5875 6005 6141');
SELECT setval(pg_get_serial_sequence('realmlist', 'id'), 1, true);
CREATE TABLE realmcharacters (
    realmid BIGINT NOT NULL CHECK (realmid >= 0), acctid BIGINT NOT NULL CHECK (acctid >= 0),
    numchars SMALLINT NOT NULL DEFAULT 0 CHECK (numchars >= 0), PRIMARY KEY (realmid, acctid)
);
CREATE INDEX idx_realmcharacters_acctid ON realmcharacters (acctid);
CREATE TABLE allowed_clients (
    major_version SMALLINT NOT NULL CHECK (major_version >= 0), minor_version SMALLINT NOT NULL CHECK (minor_version >= 0),
    bugfix_version SMALLINT NOT NULL CHECK (bugfix_version >= 0), hotfix_version CHAR(1) NOT NULL,
    build INTEGER NOT NULL CHECK (build >= 0), os CHAR(50) NOT NULL, platform CHAR(50) NOT NULL,
    integrity_hash VARCHAR(40) NOT NULL DEFAULT ''
);
INSERT INTO allowed_clients VALUES
    (3,3,5,'a',13930,'Win','x86',''), (3,3,5,'a',13930,'OSX','x86',''), (3,3,5,'a',13930,'OSX','PPC',''),
    (3,3,5,'a',12340,'Win','x86','CDCBBD5188315E6B4D19449D492DBCFAF156A347'),
    (1,12,3,'',6141,'Win','x86','2E5236E566AEA9BFFA0CC041679C2DB52E21C9DC');
CREATE TABLE uptime (realmid BIGINT NOT NULL CHECK (realmid >= 0), starttime BIGINT NOT NULL CHECK (starttime >= 0), startstring VARCHAR(64) NOT NULL DEFAULT '', uptime BIGINT NOT NULL DEFAULT 0 CHECK (uptime >= 0), onlineplayers INTEGER NOT NULL DEFAULT 0 CHECK (onlineplayers >= 0), maxplayers INTEGER NOT NULL DEFAULT 0 CHECK (maxplayers >= 0), revision VARCHAR(255) NOT NULL DEFAULT 'VMangos', PRIMARY KEY (realmid, starttime));
CREATE TABLE geoip (network_start_integer INTEGER, network_last_integer INTEGER, geoname_id TEXT, registered_country_geoname_id TEXT, represented_country_geoname_id TEXT, is_anonymous_proxy INTEGER, is_satellite_provider INTEGER, postal_code TEXT, latitude DOUBLE PRECISION, longitude DOUBLE PRECISION, accuracy_radius INTEGER);
CREATE INDEX idx_geoip_start ON geoip (network_start_integer); CREATE INDEX idx_geoip_end ON geoip (network_last_integer);
CREATE TABLE ip2nation (ip BIGINT NOT NULL DEFAULT 0 CHECK (ip >= 0), country CHAR(2) NOT NULL DEFAULT ''); CREATE INDEX idx_ip2nation_ip ON ip2nation (ip);
CREATE TABLE ip2nationcountries (code VARCHAR(4) PRIMARY KEY DEFAULT '', iso_code_2 VARCHAR(2) NOT NULL DEFAULT '', iso_code_3 VARCHAR(3) DEFAULT '', iso_country VARCHAR(255) NOT NULL DEFAULT '', country VARCHAR(255) NOT NULL DEFAULT '', lat REAL NOT NULL DEFAULT 0, lon REAL NOT NULL DEFAULT 0);
