-- PostgreSQL migration: auth / base_tables
-- Consolidated table setup for the auth schema.

CREATE TABLE account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY CHECK (id >= 0),
    username VARCHAR(32) NOT NULL UNIQUE,
    gmlevel SMALLINT NOT NULL DEFAULT 0 CHECK (gmlevel >= 0),
    sessionkey TEXT, v TEXT, s TEXT,
    reg_mail VARCHAR(255) NOT NULL DEFAULT '', token_key VARCHAR(100) NOT NULL DEFAULT '',
    email TEXT, joindate TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_ip VARCHAR(45) NOT NULL DEFAULT '0.0.0.0',
    last_attempt_ip VARCHAR(45) NOT NULL DEFAULT '127.0.0.1',
    last_local_ip VARCHAR(45) NOT NULL DEFAULT '127.0.0.1',
    failed_logins BIGINT NOT NULL DEFAULT 0 CHECK (failed_logins >= 0),
    locked SMALLINT NOT NULL DEFAULT 0 CHECK (locked >= 0), lock_country VARCHAR(2) NOT NULL DEFAULT '00',
    last_login TIMESTAMPTZ NOT NULL DEFAULT '1970-01-01 00:00:01+00',
    last_pwd_reset TIMESTAMPTZ NOT NULL DEFAULT '1970-01-01 00:00:01+00',
    online SMALLINT NOT NULL DEFAULT 0 CHECK (online >= 0), expansion SMALLINT NOT NULL DEFAULT 0 CHECK (expansion >= 0),
    mutetime BIGINT NOT NULL DEFAULT 0, mutereason VARCHAR(255) NOT NULL DEFAULT '', muteby VARCHAR(50) NOT NULL DEFAULT '',
    locale SMALLINT NOT NULL DEFAULT 0 CHECK (locale >= 0), os VARCHAR(4) NOT NULL DEFAULT '', platform VARCHAR(4) NOT NULL DEFAULT '',
    recruiter INTEGER NOT NULL DEFAULT 0, current_realm SMALLINT NOT NULL DEFAULT 0 CHECK (current_realm >= 0),
    banned SMALLINT NOT NULL DEFAULT 0 CHECK (banned >= 0), mail_verif SMALLINT NOT NULL DEFAULT 0 CHECK (mail_verif >= 0),
    remember_token VARCHAR(100) NOT NULL DEFAULT '', flags BIGINT NOT NULL DEFAULT 0 CHECK (flags >= 0),
    security VARCHAR(255), pass_verif VARCHAR(255), email_verif BOOLEAN NOT NULL DEFAULT FALSE, email_check VARCHAR(255),
    nostalrius_token VARCHAR(255), nostalrius_token_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    nostalrius_email TEXT, nostalrius_reason TEXT, geolock_pin INTEGER DEFAULT 0, totp_secret VARCHAR(255),
    bnet_srp_version SMALLINT NOT NULL DEFAULT 2 CHECK (bnet_srp_version >= 0),
    bnet_salt VARCHAR(64), bnet_verifier VARCHAR(512), bnet_login_ticket VARCHAR(64),
    bnet_login_ticket_expiry BIGINT NOT NULL DEFAULT 0
);
CREATE INDEX idx_account_gmlevel ON account (gmlevel);
CREATE INDEX idx_account_bnet_login_ticket ON account (bnet_login_ticket);

CREATE TABLE account_access (
    id BIGINT NOT NULL CHECK (id >= 0), gmlevel SMALLINT NOT NULL CHECK (gmlevel >= 0),
    "RealmID" INTEGER NOT NULL, PRIMARY KEY (id, "RealmID")
);
CREATE TABLE account_banned (
    banid BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
    id BIGINT NOT NULL DEFAULT 0 CHECK (id >= 0), bandate BIGINT NOT NULL DEFAULT 0,
    unbandate BIGINT NOT NULL DEFAULT 0, bannedby VARCHAR(50) NOT NULL, banreason VARCHAR(255) NOT NULL,
    active SMALLINT NOT NULL DEFAULT 1, realm SMALLINT NOT NULL DEFAULT 1, gmlevel SMALLINT NOT NULL DEFAULT 0 CHECK (gmlevel >= 0),
    PRIMARY KEY (id, bandate)
);
CREATE TABLE ip_banned (
    ip VARCHAR(45) PRIMARY KEY DEFAULT '0.0.0.0', bandate BIGINT NOT NULL, unbandate BIGINT NOT NULL,
    bannedby VARCHAR(50) NOT NULL DEFAULT '[Console]', banreason VARCHAR(255) NOT NULL DEFAULT 'no reason'
);
CREATE TABLE realmlist (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY CHECK (id >= 0), name VARCHAR(32) NOT NULL DEFAULT '' UNIQUE,
    address VARCHAR(45) NOT NULL DEFAULT '127.0.0.1', "localAddress" VARCHAR(255) NOT NULL DEFAULT '127.0.0.1',
    "localSubnetMask" VARCHAR(255) NOT NULL DEFAULT '255.255.255.0', port INTEGER NOT NULL DEFAULT 8085,
    icon SMALLINT NOT NULL DEFAULT 0 CHECK (icon >= 0), realmflags SMALLINT NOT NULL DEFAULT 2 CHECK (realmflags >= 0),
    timezone SMALLINT NOT NULL DEFAULT 0 CHECK (timezone >= 0), "allowedSecurityLevel" SMALLINT NOT NULL DEFAULT 0 CHECK ("allowedSecurityLevel" >= 0),
    population REAL NOT NULL DEFAULT 0, gamebuild_min BIGINT NOT NULL DEFAULT 0 CHECK (gamebuild_min >= 0),
    gamebuild_max BIGINT NOT NULL DEFAULT 0 CHECK (gamebuild_max >= 0), flag SMALLINT NOT NULL DEFAULT 2 CHECK (flag >= 0),
    realmbuilds VARCHAR(64) NOT NULL DEFAULT '', last_seen TIMESTAMPTZ
);
CREATE TABLE realmcharacters (
    realmid BIGINT NOT NULL CHECK (realmid >= 0), acctid BIGINT NOT NULL CHECK (acctid >= 0),
    numchars SMALLINT NOT NULL DEFAULT 0 CHECK (numchars >= 0), PRIMARY KEY (realmid, acctid)
);
CREATE INDEX idx_realmcharacters_acctid ON realmcharacters (acctid);
CREATE TABLE allowed_clients (
    major_version SMALLINT NOT NULL CHECK (major_version >= 0), minor_version SMALLINT NOT NULL CHECK (minor_version >= 0),
    bugfix_version SMALLINT NOT NULL CHECK (bugfix_version >= 0), hotfix_version CHAR(1) NOT NULL,
    build BIGINT NOT NULL CHECK (build >= 0), os CHAR(50) NOT NULL, platform CHAR(50) NOT NULL,
    integrity_hash VARCHAR(40) NOT NULL DEFAULT ''
);
CREATE TABLE uptime (realmid BIGINT NOT NULL CHECK (realmid >= 0), starttime BIGINT NOT NULL CHECK (starttime >= 0), startstring VARCHAR(64) NOT NULL DEFAULT '', uptime BIGINT NOT NULL DEFAULT 0 CHECK (uptime >= 0), onlineplayers INTEGER NOT NULL DEFAULT 0 CHECK (onlineplayers >= 0), maxplayers INTEGER NOT NULL DEFAULT 0 CHECK (maxplayers >= 0), revision VARCHAR(255) NOT NULL DEFAULT 'VMangos', PRIMARY KEY (realmid, starttime));
CREATE TABLE geoip (network_start_integer INTEGER, network_last_integer INTEGER, geoname_id TEXT, registered_country_geoname_id TEXT, represented_country_geoname_id TEXT, is_anonymous_proxy INTEGER, is_satellite_provider INTEGER, postal_code TEXT, latitude DOUBLE PRECISION, longitude DOUBLE PRECISION, accuracy_radius INTEGER);
CREATE INDEX idx_geoip_start ON geoip (network_start_integer); CREATE INDEX idx_geoip_end ON geoip (network_last_integer);
CREATE TABLE ip2nation (ip BIGINT NOT NULL DEFAULT 0 CHECK (ip >= 0), country CHAR(2) NOT NULL DEFAULT ''); CREATE INDEX idx_ip2nation_ip ON ip2nation (ip);
CREATE TABLE ip2nationcountries (code VARCHAR(4) PRIMARY KEY DEFAULT '', iso_code_2 VARCHAR(2) NOT NULL DEFAULT '', iso_code_3 VARCHAR(3) DEFAULT '', iso_country VARCHAR(255) NOT NULL DEFAULT '', country VARCHAR(255) NOT NULL DEFAULT '', lat REAL NOT NULL DEFAULT 0, lon REAL NOT NULL DEFAULT 0);
-- Consolidated legacy table coverage retained from the previous setup migration
-- Generated schema DDL only; it contains no reference data.

CREATE TABLE IF NOT EXISTS "account" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL CHECK ("id" >= 0),
    "username" VARCHAR(32) NOT NULL,
    "gmlevel" SMALLINT NOT NULL DEFAULT '0' CHECK ("gmlevel" >= 0),
    "sessionkey" TEXT,
    "v" TEXT,
    "s" TEXT,
    "reg_mail" VARCHAR(255) NOT NULL DEFAULT '',
    "token_key" VARCHAR(100) NOT NULL DEFAULT '',
    "email" TEXT,
    "joindate" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "last_ip" VARCHAR(30) NOT NULL DEFAULT '0.0.0.0',
    "last_attempt_ip" VARCHAR(15) NOT NULL DEFAULT '127.0.0.1',
    "last_local_ip" VARCHAR(30) NOT NULL DEFAULT '127.0.0.1',
    "failed_logins" BIGINT NOT NULL DEFAULT '0' CHECK ("failed_logins" >= 0),
    "locked" SMALLINT NOT NULL DEFAULT '0' CHECK ("locked" >= 0),
    "lock_country" VARCHAR(2) NOT NULL DEFAULT '00',
    "last_login" TIMESTAMP NOT NULL DEFAULT '1970-01-01 00:00:01',
    "last_pwd_reset" TIMESTAMP NOT NULL DEFAULT '1970-01-01 00:00:01',
    "online" SMALLINT NOT NULL DEFAULT '0' CHECK ("online" >= 0),
    "expansion" SMALLINT NOT NULL DEFAULT '0' CHECK ("expansion" >= 0),
    "mutetime" BIGINT NOT NULL DEFAULT '0',
    "mutereason" VARCHAR(255) NOT NULL DEFAULT '',
    "muteby" VARCHAR(50) NOT NULL DEFAULT '',
    "locale" SMALLINT NOT NULL DEFAULT '0' CHECK ("locale" >= 0),
    "os" VARCHAR(4) NOT NULL DEFAULT '',
    "platform" VARCHAR(4) NOT NULL DEFAULT '',
    "recruiter" INTEGER NOT NULL DEFAULT '0',
    "current_realm" SMALLINT NOT NULL DEFAULT '0' CHECK ("current_realm" >= 0),
    "banned" SMALLINT NOT NULL DEFAULT '0' CHECK ("banned" >= 0),
    "mail_verif" SMALLINT NOT NULL DEFAULT '0' CHECK ("mail_verif" >= 0),
    "remember_token" VARCHAR(100) NOT NULL DEFAULT '',
    "flags" BIGINT NOT NULL DEFAULT '0' CHECK ("flags" >= 0),
    "security" VARCHAR(255) DEFAULT NULL,
    "pass_verif" VARCHAR(255) DEFAULT NULL,
    "email_verif" SMALLINT NOT NULL DEFAULT '0',
    "email_check" VARCHAR(255) DEFAULT NULL,
    "nostalrius_token" VARCHAR(255) DEFAULT NULL,
    "nostalrius_token_enabled" SMALLINT NOT NULL DEFAULT '0',
    "nostalrius_email" TEXT,
    "nostalrius_reason" TEXT,
    "geolock_pin" INTEGER DEFAULT '0',
    "totp_secret" VARCHAR(255) DEFAULT NULL,
    "bnet_srp_version" SMALLINT NOT NULL DEFAULT '2' CHECK ("bnet_srp_version" >= 0),
    "bnet_salt" VARCHAR(64) DEFAULT NULL,
    "bnet_verifier" VARCHAR(512) DEFAULT NULL,
    "bnet_login_ticket" VARCHAR(64) DEFAULT NULL,
    "bnet_login_ticket_expiry" BIGINT NOT NULL DEFAULT '0',
    PRIMARY KEY ("id"),
    UNIQUE ("username")
);
ALTER TABLE IF EXISTS "account" ADD COLUMN IF NOT EXISTS "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL CHECK ("id" >= 0);
ALTER TABLE IF EXISTS "account" ADD COLUMN IF NOT EXISTS "username" VARCHAR(32) NOT NULL;
ALTER TABLE IF EXISTS "account" ADD COLUMN IF NOT EXISTS "gmlevel" SMALLINT NOT NULL DEFAULT '0' CHECK ("gmlevel" >= 0);
ALTER TABLE IF EXISTS "account" ADD COLUMN IF NOT EXISTS "sessionkey" TEXT;
ALTER TABLE IF EXISTS "account" ADD COLUMN IF NOT EXISTS "v" TEXT;
ALTER TABLE IF EXISTS "account" ADD COLUMN IF NOT EXISTS "s" TEXT;
ALTER TABLE IF EXISTS "account" ADD COLUMN IF NOT EXISTS "reg_mail" VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE IF EXISTS "account" ADD COLUMN IF NOT EXISTS "token_key" VARCHAR(100) NOT NULL DEFAULT '';
ALTER TABLE IF EXISTS "account" ADD COLUMN IF NOT EXISTS "email" TEXT;
ALTER TABLE IF EXISTS "account" ADD COLUMN IF NOT EXISTS "joindate" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS "account" ADD COLUMN IF NOT EXISTS "last_ip" VARCHAR(30) NOT NULL DEFAULT '0.0.0.0';
ALTER TABLE IF EXISTS "account" ADD COLUMN IF NOT EXISTS "last_attempt_ip" VARCHAR(15) NOT NULL DEFAULT '127.0.0.1';
ALTER TABLE IF EXISTS "account" ADD COLUMN IF NOT EXISTS "last_local_ip" VARCHAR(30) NOT NULL DEFAULT '127.0.0.1';
ALTER TABLE IF EXISTS "account" ADD COLUMN IF NOT EXISTS "failed_logins" BIGINT NOT NULL DEFAULT '0' CHECK ("failed_logins" >= 0);
ALTER TABLE IF EXISTS "account" ADD COLUMN IF NOT EXISTS "locked" SMALLINT NOT NULL DEFAULT '0' CHECK ("locked" >= 0);
ALTER TABLE IF EXISTS "account" ADD COLUMN IF NOT EXISTS "lock_country" VARCHAR(2) NOT NULL DEFAULT '00';
ALTER TABLE IF EXISTS "account" ADD COLUMN IF NOT EXISTS "last_login" TIMESTAMP NOT NULL DEFAULT '1970-01-01 00:00:01';
ALTER TABLE IF EXISTS "account" ADD COLUMN IF NOT EXISTS "last_pwd_reset" TIMESTAMP NOT NULL DEFAULT '1970-01-01 00:00:01';
ALTER TABLE IF EXISTS "account" ADD COLUMN IF NOT EXISTS "online" SMALLINT NOT NULL DEFAULT '0' CHECK ("online" >= 0);
ALTER TABLE IF EXISTS "account" ADD COLUMN IF NOT EXISTS "expansion" SMALLINT NOT NULL DEFAULT '0' CHECK ("expansion" >= 0);
ALTER TABLE IF EXISTS "account" ADD COLUMN IF NOT EXISTS "mutetime" BIGINT NOT NULL DEFAULT '0';
ALTER TABLE IF EXISTS "account" ADD COLUMN IF NOT EXISTS "mutereason" VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE IF EXISTS "account" ADD COLUMN IF NOT EXISTS "muteby" VARCHAR(50) NOT NULL DEFAULT '';
ALTER TABLE IF EXISTS "account" ADD COLUMN IF NOT EXISTS "locale" SMALLINT NOT NULL DEFAULT '0' CHECK ("locale" >= 0);
ALTER TABLE IF EXISTS "account" ADD COLUMN IF NOT EXISTS "os" VARCHAR(4) NOT NULL DEFAULT '';
ALTER TABLE IF EXISTS "account" ADD COLUMN IF NOT EXISTS "platform" VARCHAR(4) NOT NULL DEFAULT '';
ALTER TABLE IF EXISTS "account" ADD COLUMN IF NOT EXISTS "recruiter" INTEGER NOT NULL DEFAULT '0';
ALTER TABLE IF EXISTS "account" ADD COLUMN IF NOT EXISTS "current_realm" SMALLINT NOT NULL DEFAULT '0' CHECK ("current_realm" >= 0);
ALTER TABLE IF EXISTS "account" ADD COLUMN IF NOT EXISTS "banned" SMALLINT NOT NULL DEFAULT '0' CHECK ("banned" >= 0);
ALTER TABLE IF EXISTS "account" ADD COLUMN IF NOT EXISTS "mail_verif" SMALLINT NOT NULL DEFAULT '0' CHECK ("mail_verif" >= 0);
ALTER TABLE IF EXISTS "account" ADD COLUMN IF NOT EXISTS "remember_token" VARCHAR(100) NOT NULL DEFAULT '';
ALTER TABLE IF EXISTS "account" ADD COLUMN IF NOT EXISTS "flags" BIGINT NOT NULL DEFAULT '0' CHECK ("flags" >= 0);
ALTER TABLE IF EXISTS "account" ADD COLUMN IF NOT EXISTS "security" VARCHAR(255) DEFAULT NULL;
ALTER TABLE IF EXISTS "account" ADD COLUMN IF NOT EXISTS "pass_verif" VARCHAR(255) DEFAULT NULL;
ALTER TABLE IF EXISTS "account" ADD COLUMN IF NOT EXISTS "email_verif" SMALLINT NOT NULL DEFAULT '0';
ALTER TABLE IF EXISTS "account" ADD COLUMN IF NOT EXISTS "email_check" VARCHAR(255) DEFAULT NULL;
ALTER TABLE IF EXISTS "account" ADD COLUMN IF NOT EXISTS "nostalrius_token" VARCHAR(255) DEFAULT NULL;
ALTER TABLE IF EXISTS "account" ADD COLUMN IF NOT EXISTS "nostalrius_token_enabled" SMALLINT NOT NULL DEFAULT '0';
ALTER TABLE IF EXISTS "account" ADD COLUMN IF NOT EXISTS "nostalrius_email" TEXT;
ALTER TABLE IF EXISTS "account" ADD COLUMN IF NOT EXISTS "nostalrius_reason" TEXT;
ALTER TABLE IF EXISTS "account" ADD COLUMN IF NOT EXISTS "geolock_pin" INTEGER DEFAULT '0';
ALTER TABLE IF EXISTS "account" ADD COLUMN IF NOT EXISTS "totp_secret" VARCHAR(255) DEFAULT NULL;
ALTER TABLE IF EXISTS "account" ADD COLUMN IF NOT EXISTS "bnet_srp_version" SMALLINT NOT NULL DEFAULT '2' CHECK ("bnet_srp_version" >= 0);
ALTER TABLE IF EXISTS "account" ADD COLUMN IF NOT EXISTS "bnet_salt" VARCHAR(64) DEFAULT NULL;
ALTER TABLE IF EXISTS "account" ADD COLUMN IF NOT EXISTS "bnet_verifier" VARCHAR(512) DEFAULT NULL;
ALTER TABLE IF EXISTS "account" ADD COLUMN IF NOT EXISTS "bnet_login_ticket" VARCHAR(64) DEFAULT NULL;
ALTER TABLE IF EXISTS "account" ADD COLUMN IF NOT EXISTS "bnet_login_ticket_expiry" BIGINT NOT NULL DEFAULT '0';
CREATE UNIQUE INDEX IF NOT EXISTS idx_account_idx_username ON "account" ("username");
CREATE INDEX IF NOT EXISTS idx_account_idx_gmlevel ON "account" ("gmlevel");
CREATE INDEX IF NOT EXISTS idx_account_idx_bnet_login_ticket ON "account" ("bnet_login_ticket");

CREATE TABLE IF NOT EXISTS "account_access" (
    "id" BIGINT NOT NULL CHECK ("id" >= 0),
    "gmlevel" SMALLINT NOT NULL CHECK ("gmlevel" >= 0),
    "RealmID" INTEGER NOT NULL,
    PRIMARY KEY ("id", "RealmID")
);
ALTER TABLE IF EXISTS "account_access" ADD COLUMN IF NOT EXISTS "id" BIGINT NOT NULL CHECK ("id" >= 0);
ALTER TABLE IF EXISTS "account_access" ADD COLUMN IF NOT EXISTS "gmlevel" SMALLINT NOT NULL CHECK ("gmlevel" >= 0);
ALTER TABLE IF EXISTS "account_access" ADD COLUMN IF NOT EXISTS "RealmID" INTEGER NOT NULL;

CREATE TABLE IF NOT EXISTS "account_banned" (
    "banid" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "id" BIGINT NOT NULL DEFAULT '0',
    "bandate" BIGINT NOT NULL DEFAULT '0',
    "unbandate" BIGINT NOT NULL DEFAULT '0',
    "bannedby" VARCHAR(50) NOT NULL,
    "banreason" VARCHAR(255) NOT NULL,
    "active" SMALLINT NOT NULL DEFAULT '1',
    "realm" SMALLINT NOT NULL DEFAULT '1',
    "gmlevel" SMALLINT NOT NULL DEFAULT '0' CHECK ("gmlevel" >= 0),
    PRIMARY KEY ("id", "bandate"),
    UNIQUE ("banid")
);
ALTER TABLE IF EXISTS "account_banned" ADD COLUMN IF NOT EXISTS "banid" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL;
ALTER TABLE IF EXISTS "account_banned" ADD COLUMN IF NOT EXISTS "id" BIGINT NOT NULL DEFAULT '0';
ALTER TABLE IF EXISTS "account_banned" ADD COLUMN IF NOT EXISTS "bandate" BIGINT NOT NULL DEFAULT '0';
ALTER TABLE IF EXISTS "account_banned" ADD COLUMN IF NOT EXISTS "unbandate" BIGINT NOT NULL DEFAULT '0';
ALTER TABLE IF EXISTS "account_banned" ADD COLUMN IF NOT EXISTS "bannedby" VARCHAR(50) NOT NULL;
ALTER TABLE IF EXISTS "account_banned" ADD COLUMN IF NOT EXISTS "banreason" VARCHAR(255) NOT NULL;
ALTER TABLE IF EXISTS "account_banned" ADD COLUMN IF NOT EXISTS "active" SMALLINT NOT NULL DEFAULT '1';
ALTER TABLE IF EXISTS "account_banned" ADD COLUMN IF NOT EXISTS "realm" SMALLINT NOT NULL DEFAULT '1';
ALTER TABLE IF EXISTS "account_banned" ADD COLUMN IF NOT EXISTS "gmlevel" SMALLINT NOT NULL DEFAULT '0' CHECK ("gmlevel" >= 0);
CREATE UNIQUE INDEX IF NOT EXISTS idx_account_banned_banid ON "account_banned" ("banid");

CREATE TABLE IF NOT EXISTS "allowed_clients" (
    "major_version" SMALLINT NOT NULL CHECK ("major_version" >= 0),
    "minor_version" SMALLINT NOT NULL CHECK ("minor_version" >= 0),
    "bugfix_version" SMALLINT NOT NULL CHECK ("bugfix_version" >= 0),
    "hotfix_version" CHAR(1) NOT NULL,
    "build" BIGINT NOT NULL CHECK ("build" >= 0),
    "os" CHAR(50) NOT NULL,
    "platform" CHAR(50) NOT NULL,
    "integrity_hash" VARCHAR(40) NOT NULL DEFAULT ''
);
ALTER TABLE IF EXISTS "allowed_clients" ADD COLUMN IF NOT EXISTS "major_version" SMALLINT NOT NULL CHECK ("major_version" >= 0);
ALTER TABLE IF EXISTS "allowed_clients" ADD COLUMN IF NOT EXISTS "minor_version" SMALLINT NOT NULL CHECK ("minor_version" >= 0);
ALTER TABLE IF EXISTS "allowed_clients" ADD COLUMN IF NOT EXISTS "bugfix_version" SMALLINT NOT NULL CHECK ("bugfix_version" >= 0);
ALTER TABLE IF EXISTS "allowed_clients" ADD COLUMN IF NOT EXISTS "hotfix_version" CHAR(1) NOT NULL;
ALTER TABLE IF EXISTS "allowed_clients" ADD COLUMN IF NOT EXISTS "build" BIGINT NOT NULL CHECK ("build" >= 0);
ALTER TABLE IF EXISTS "allowed_clients" ADD COLUMN IF NOT EXISTS "os" CHAR(50) NOT NULL;
ALTER TABLE IF EXISTS "allowed_clients" ADD COLUMN IF NOT EXISTS "platform" CHAR(50) NOT NULL;
ALTER TABLE IF EXISTS "allowed_clients" ADD COLUMN IF NOT EXISTS "integrity_hash" VARCHAR(40) NOT NULL DEFAULT '';

CREATE TABLE IF NOT EXISTS "geoip" (
    "network_start_integer" INTEGER DEFAULT NULL,
    "network_last_integer" INTEGER DEFAULT NULL,
    "geoname_id" TEXT,
    "registered_country_geoname_id" TEXT,
    "represented_country_geoname_id" TEXT,
    "is_anonymous_proxy" INTEGER DEFAULT NULL,
    "is_satellite_provider" INTEGER DEFAULT NULL,
    "postal_code" TEXT,
    "latitude" DOUBLE PRECISION DEFAULT NULL,
    "longitude" DOUBLE PRECISION DEFAULT NULL,
    "accuracy_radius" INTEGER DEFAULT NULL
);
ALTER TABLE IF EXISTS "geoip" ADD COLUMN IF NOT EXISTS "network_start_integer" INTEGER DEFAULT NULL;
ALTER TABLE IF EXISTS "geoip" ADD COLUMN IF NOT EXISTS "network_last_integer" INTEGER DEFAULT NULL;
ALTER TABLE IF EXISTS "geoip" ADD COLUMN IF NOT EXISTS "geoname_id" TEXT;
ALTER TABLE IF EXISTS "geoip" ADD COLUMN IF NOT EXISTS "registered_country_geoname_id" TEXT;
ALTER TABLE IF EXISTS "geoip" ADD COLUMN IF NOT EXISTS "represented_country_geoname_id" TEXT;
ALTER TABLE IF EXISTS "geoip" ADD COLUMN IF NOT EXISTS "is_anonymous_proxy" INTEGER DEFAULT NULL;
ALTER TABLE IF EXISTS "geoip" ADD COLUMN IF NOT EXISTS "is_satellite_provider" INTEGER DEFAULT NULL;
ALTER TABLE IF EXISTS "geoip" ADD COLUMN IF NOT EXISTS "postal_code" TEXT;
ALTER TABLE IF EXISTS "geoip" ADD COLUMN IF NOT EXISTS "latitude" DOUBLE PRECISION DEFAULT NULL;
ALTER TABLE IF EXISTS "geoip" ADD COLUMN IF NOT EXISTS "longitude" DOUBLE PRECISION DEFAULT NULL;
ALTER TABLE IF EXISTS "geoip" ADD COLUMN IF NOT EXISTS "accuracy_radius" INTEGER DEFAULT NULL;
CREATE INDEX IF NOT EXISTS idx_geoip_ip_start ON "geoip" ("network_start_integer");
CREATE INDEX IF NOT EXISTS idx_geoip_ip_end ON "geoip" ("network_last_integer");

CREATE TABLE IF NOT EXISTS "ip2nation" (
    "ip" BIGINT NOT NULL DEFAULT '0' CHECK ("ip" >= 0),
    "country" CHAR(2) NOT NULL DEFAULT ''
);
ALTER TABLE IF EXISTS "ip2nation" ADD COLUMN IF NOT EXISTS "ip" BIGINT NOT NULL DEFAULT '0' CHECK ("ip" >= 0);
ALTER TABLE IF EXISTS "ip2nation" ADD COLUMN IF NOT EXISTS "country" CHAR(2) NOT NULL DEFAULT '';
CREATE INDEX IF NOT EXISTS idx_ip2nation_ip ON "ip2nation" ("ip");

CREATE TABLE IF NOT EXISTS "ip2nationcountries" (
    "code" VARCHAR(4) NOT NULL DEFAULT '',
    "iso_code_2" VARCHAR(2) NOT NULL DEFAULT '',
    "iso_code_3" VARCHAR(3) DEFAULT '',
    "iso_country" VARCHAR(255) NOT NULL DEFAULT '',
    "country" VARCHAR(255) NOT NULL DEFAULT '',
    "lat" REAL NOT NULL DEFAULT '0',
    "lon" REAL NOT NULL DEFAULT '0',
    PRIMARY KEY ("code")
);
ALTER TABLE IF EXISTS "ip2nationcountries" ADD COLUMN IF NOT EXISTS "code" VARCHAR(4) NOT NULL DEFAULT '';
ALTER TABLE IF EXISTS "ip2nationcountries" ADD COLUMN IF NOT EXISTS "iso_code_2" VARCHAR(2) NOT NULL DEFAULT '';
ALTER TABLE IF EXISTS "ip2nationcountries" ADD COLUMN IF NOT EXISTS "iso_code_3" VARCHAR(3) DEFAULT '';
ALTER TABLE IF EXISTS "ip2nationcountries" ADD COLUMN IF NOT EXISTS "iso_country" VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE IF EXISTS "ip2nationcountries" ADD COLUMN IF NOT EXISTS "country" VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE IF EXISTS "ip2nationcountries" ADD COLUMN IF NOT EXISTS "lat" REAL NOT NULL DEFAULT '0';
ALTER TABLE IF EXISTS "ip2nationcountries" ADD COLUMN IF NOT EXISTS "lon" REAL NOT NULL DEFAULT '0';
CREATE INDEX IF NOT EXISTS idx_ip2nationcountries_code ON "ip2nationcountries" ("code");

CREATE TABLE IF NOT EXISTS "ip_banned" (
    "ip" VARCHAR(32) NOT NULL DEFAULT '0.0.0.0',
    "bandate" BIGINT NOT NULL,
    "unbandate" BIGINT NOT NULL,
    "bannedby" VARCHAR(50) NOT NULL DEFAULT '[Console]',
    "banreason" VARCHAR(50) NOT NULL DEFAULT 'no reason',
    PRIMARY KEY ("ip")
);
ALTER TABLE IF EXISTS "ip_banned" ADD COLUMN IF NOT EXISTS "ip" VARCHAR(32) NOT NULL DEFAULT '0.0.0.0';
ALTER TABLE IF EXISTS "ip_banned" ADD COLUMN IF NOT EXISTS "bandate" BIGINT NOT NULL;
ALTER TABLE IF EXISTS "ip_banned" ADD COLUMN IF NOT EXISTS "unbandate" BIGINT NOT NULL;
ALTER TABLE IF EXISTS "ip_banned" ADD COLUMN IF NOT EXISTS "bannedby" VARCHAR(50) NOT NULL DEFAULT '[Console]';
ALTER TABLE IF EXISTS "ip_banned" ADD COLUMN IF NOT EXISTS "banreason" VARCHAR(50) NOT NULL DEFAULT 'no reason';

CREATE TABLE IF NOT EXISTS "rbac_account_permissions" (
    "account_id" INTEGER NOT NULL,
    "permission_id" INTEGER NOT NULL,
    "granted" SMALLINT NOT NULL DEFAULT '1' CHECK ("granted" >= 0),
    PRIMARY KEY ("account_id", "permission_id")
);
ALTER TABLE IF EXISTS "rbac_account_permissions" ADD COLUMN IF NOT EXISTS "account_id" INTEGER NOT NULL;
ALTER TABLE IF EXISTS "rbac_account_permissions" ADD COLUMN IF NOT EXISTS "permission_id" INTEGER NOT NULL;
ALTER TABLE IF EXISTS "rbac_account_permissions" ADD COLUMN IF NOT EXISTS "granted" SMALLINT NOT NULL DEFAULT '1' CHECK ("granted" >= 0);

CREATE TABLE IF NOT EXISTS "rbac_command_permissions" (
    "command" VARCHAR(128) NOT NULL,
    "permission_id" BIGINT NOT NULL CHECK ("permission_id" >= 0),
    PRIMARY KEY ("command", "permission_id")
);
ALTER TABLE IF EXISTS "rbac_command_permissions" ADD COLUMN IF NOT EXISTS "command" VARCHAR(128) NOT NULL;
ALTER TABLE IF EXISTS "rbac_command_permissions" ADD COLUMN IF NOT EXISTS "permission_id" BIGINT NOT NULL CHECK ("permission_id" >= 0);

CREATE TABLE IF NOT EXISTS "rbac_permissions" (
    "id" BIGINT NOT NULL CHECK ("id" >= 0),
    "name" VARCHAR(64) NOT NULL,
    PRIMARY KEY ("id")
);
ALTER TABLE IF EXISTS "rbac_permissions" ADD COLUMN IF NOT EXISTS "id" BIGINT NOT NULL CHECK ("id" >= 0);
ALTER TABLE IF EXISTS "rbac_permissions" ADD COLUMN IF NOT EXISTS "name" VARCHAR(64) NOT NULL;

CREATE TABLE IF NOT EXISTS "realmcharacters" (
    "realmid" BIGINT NOT NULL DEFAULT '0' CHECK ("realmid" >= 0),
    "acctid" BIGINT NOT NULL CHECK ("acctid" >= 0),
    "numchars" SMALLINT NOT NULL DEFAULT '0' CHECK ("numchars" >= 0),
    PRIMARY KEY ("realmid", "acctid")
);
ALTER TABLE IF EXISTS "realmcharacters" ADD COLUMN IF NOT EXISTS "realmid" BIGINT NOT NULL DEFAULT '0' CHECK ("realmid" >= 0);
ALTER TABLE IF EXISTS "realmcharacters" ADD COLUMN IF NOT EXISTS "acctid" BIGINT NOT NULL CHECK ("acctid" >= 0);
ALTER TABLE IF EXISTS "realmcharacters" ADD COLUMN IF NOT EXISTS "numchars" SMALLINT NOT NULL DEFAULT '0' CHECK ("numchars" >= 0);
CREATE INDEX IF NOT EXISTS idx_realmcharacters_acctid ON "realmcharacters" ("acctid");

CREATE TABLE IF NOT EXISTS "realmlist" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL CHECK ("id" >= 0),
    "name" VARCHAR(32) NOT NULL DEFAULT '',
    "address" VARCHAR(32) NOT NULL DEFAULT '127.0.0.1',
    "localAddress" VARCHAR(255) NOT NULL DEFAULT '127.0.0.1',
    "localSubnetMask" VARCHAR(255) NOT NULL DEFAULT '255.255.255.0',
    "port" INTEGER NOT NULL DEFAULT '8085',
    "icon" SMALLINT NOT NULL DEFAULT '0' CHECK ("icon" >= 0),
    "realmflags" SMALLINT NOT NULL DEFAULT '2' CHECK ("realmflags" >= 0),
    "timezone" SMALLINT NOT NULL DEFAULT '0' CHECK ("timezone" >= 0),
    "allowedSecurityLevel" SMALLINT NOT NULL DEFAULT '0' CHECK ("allowedSecurityLevel" >= 0),
    "population" REAL NOT NULL DEFAULT '0' CHECK ("population" >= 0),
    "gamebuild_min" BIGINT NOT NULL DEFAULT '0' CHECK ("gamebuild_min" >= 0),
    "gamebuild_max" BIGINT NOT NULL DEFAULT '0' CHECK ("gamebuild_max" >= 0),
    "flag" SMALLINT NOT NULL DEFAULT '2' CHECK ("flag" >= 0),
    "realmbuilds" VARCHAR(64) NOT NULL DEFAULT '',
    "last_seen" TIMESTAMP DEFAULT NULL,
    PRIMARY KEY ("id"),
    UNIQUE ("name")
);
ALTER TABLE IF EXISTS "realmlist" ADD COLUMN IF NOT EXISTS "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL CHECK ("id" >= 0);
ALTER TABLE IF EXISTS "realmlist" ADD COLUMN IF NOT EXISTS "name" VARCHAR(32) NOT NULL DEFAULT '';
ALTER TABLE IF EXISTS "realmlist" ADD COLUMN IF NOT EXISTS "address" VARCHAR(32) NOT NULL DEFAULT '127.0.0.1';
ALTER TABLE IF EXISTS "realmlist" ADD COLUMN IF NOT EXISTS "localAddress" VARCHAR(255) NOT NULL DEFAULT '127.0.0.1';
ALTER TABLE IF EXISTS "realmlist" ADD COLUMN IF NOT EXISTS "localSubnetMask" VARCHAR(255) NOT NULL DEFAULT '255.255.255.0';
ALTER TABLE IF EXISTS "realmlist" ADD COLUMN IF NOT EXISTS "port" INTEGER NOT NULL DEFAULT '8085';
ALTER TABLE IF EXISTS "realmlist" ADD COLUMN IF NOT EXISTS "icon" SMALLINT NOT NULL DEFAULT '0' CHECK ("icon" >= 0);
ALTER TABLE IF EXISTS "realmlist" ADD COLUMN IF NOT EXISTS "realmflags" SMALLINT NOT NULL DEFAULT '2' CHECK ("realmflags" >= 0);
ALTER TABLE IF EXISTS "realmlist" ADD COLUMN IF NOT EXISTS "timezone" SMALLINT NOT NULL DEFAULT '0' CHECK ("timezone" >= 0);
ALTER TABLE IF EXISTS "realmlist" ADD COLUMN IF NOT EXISTS "allowedSecurityLevel" SMALLINT NOT NULL DEFAULT '0' CHECK ("allowedSecurityLevel" >= 0);
ALTER TABLE IF EXISTS "realmlist" ADD COLUMN IF NOT EXISTS "population" REAL NOT NULL DEFAULT '0' CHECK ("population" >= 0);
ALTER TABLE IF EXISTS "realmlist" ADD COLUMN IF NOT EXISTS "gamebuild_min" BIGINT NOT NULL DEFAULT '0' CHECK ("gamebuild_min" >= 0);
ALTER TABLE IF EXISTS "realmlist" ADD COLUMN IF NOT EXISTS "gamebuild_max" BIGINT NOT NULL DEFAULT '0' CHECK ("gamebuild_max" >= 0);
ALTER TABLE IF EXISTS "realmlist" ADD COLUMN IF NOT EXISTS "flag" SMALLINT NOT NULL DEFAULT '2' CHECK ("flag" >= 0);
ALTER TABLE IF EXISTS "realmlist" ADD COLUMN IF NOT EXISTS "realmbuilds" VARCHAR(64) NOT NULL DEFAULT '';
ALTER TABLE IF EXISTS "realmlist" ADD COLUMN IF NOT EXISTS "last_seen" TIMESTAMP DEFAULT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS idx_realmlist_idx_name ON "realmlist" ("name");

CREATE TABLE IF NOT EXISTS "uptime" (
    "realmid" BIGINT NOT NULL CHECK ("realmid" >= 0),
    "starttime" BIGINT NOT NULL DEFAULT '0' CHECK ("starttime" >= 0),
    "startstring" VARCHAR(64) NOT NULL DEFAULT '',
    "uptime" BIGINT NOT NULL DEFAULT '0' CHECK ("uptime" >= 0),
    "onlineplayers" INTEGER NOT NULL DEFAULT '0' CHECK ("onlineplayers" >= 0),
    "maxplayers" INTEGER NOT NULL DEFAULT '0' CHECK ("maxplayers" >= 0),
    "revision" VARCHAR(255) NOT NULL DEFAULT 'VMangos',
    PRIMARY KEY ("realmid", "starttime")
);
ALTER TABLE IF EXISTS "uptime" ADD COLUMN IF NOT EXISTS "realmid" BIGINT NOT NULL CHECK ("realmid" >= 0);
ALTER TABLE IF EXISTS "uptime" ADD COLUMN IF NOT EXISTS "starttime" BIGINT NOT NULL DEFAULT '0' CHECK ("starttime" >= 0);
ALTER TABLE IF EXISTS "uptime" ADD COLUMN IF NOT EXISTS "startstring" VARCHAR(64) NOT NULL DEFAULT '';
ALTER TABLE IF EXISTS "uptime" ADD COLUMN IF NOT EXISTS "uptime" BIGINT NOT NULL DEFAULT '0' CHECK ("uptime" >= 0);
ALTER TABLE IF EXISTS "uptime" ADD COLUMN IF NOT EXISTS "onlineplayers" INTEGER NOT NULL DEFAULT '0' CHECK ("onlineplayers" >= 0);
ALTER TABLE IF EXISTS "uptime" ADD COLUMN IF NOT EXISTS "maxplayers" INTEGER NOT NULL DEFAULT '0' CHECK ("maxplayers" >= 0);
ALTER TABLE IF EXISTS "uptime" ADD COLUMN IF NOT EXISTS "revision" VARCHAR(255) NOT NULL DEFAULT 'VMangos';
