CREATE TABLE `chat_log` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `channel_type` varchar(16) NOT NULL,
  `channel_name` varchar(64) DEFAULT NULL,
  `sender_guid` int unsigned DEFAULT NULL,
  `sender_name` varchar(32) DEFAULT NULL,
  `sender_account` int unsigned DEFAULT NULL,
  `target_guid` int unsigned DEFAULT NULL,
  `target_name` varchar(32) DEFAULT NULL,
  `message` varchar(512) NOT NULL,
  `map` int unsigned DEFAULT NULL,
  `pos_x` float DEFAULT NULL,
  `pos_y` float DEFAULT NULL,
  `pos_z` float DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_chat_log_time` (`time`),
  KEY `idx_chat_log_sender` (`sender_guid`),
  KEY `idx_chat_log_sender_account` (`sender_account`),
  KEY `idx_chat_log_channel` (`channel_type`, `channel_name`),
  KEY `idx_chat_log_target` (`target_guid`),
  KEY `idx_chat_log_sender_time` (`sender_guid`, `time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='chat messages';
