-- PostgreSQL migration: logs / base_tables
-- Canonical PostgreSQL logs schema used by the world and web runtimes.

CREATE TABLE instance_creature_kills (
    "mapId" BIGINT NOT NULL CHECK ("mapId" >= 0),
    "creatureEntry" BIGINT NOT NULL CHECK ("creatureEntry" >= 0),
    "spellEntry" INTEGER NOT NULL,
    count BIGINT NOT NULL CHECK (count >= 0),
    PRIMARY KEY ("mapId", "creatureEntry", "spellEntry")
);

CREATE TABLE instance_custom_counters (
    "index" BIGINT PRIMARY KEY CHECK ("index" >= 0),
    count BIGINT NOT NULL CHECK (count >= 0)
);

CREATE TABLE instance_wipes (
    "mapId" BIGINT NOT NULL CHECK ("mapId" >= 0),
    "creatureEntry" BIGINT NOT NULL CHECK ("creatureEntry" >= 0),
    count BIGINT NOT NULL CHECK (count >= 0),
    PRIMARY KEY ("mapId", "creatureEntry")
);

CREATE TABLE logs_battleground (
    time TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    bgid INTEGER,
    bgtype INTEGER,
    bgteamcount INTEGER,
    bgduration INTEGER,
    "playerGuid" INTEGER,
    team INTEGER,
    deaths INTEGER,
    "honorBonus" INTEGER,
    "honorableKills" INTEGER
);

CREATE TABLE logs_player (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    type TEXT NOT NULL CHECK (type IN (
        'Basic', 'WorldPacket', 'Chat', 'BG', 'Character', 'Honor', 'RA', 'DBError',
        'DBErrorFix', 'ClientIds', 'Loot', 'LevelUp', 'Performance', 'MoneyTrade', 'GM',
        'GMCritical', 'ChatSpam', 'Anticheat'
    )),
    subtype VARCHAR(20),
    account BIGINT NOT NULL CHECK (account >= 0),
    ip VARCHAR(16),
    guid INTEGER,
    name VARCHAR(20),
    map BIGINT CHECK (map >= 0),
    pos_x REAL,
    pos_y REAL,
    pos_z REAL,
    text VARCHAR(512) NOT NULL
);

CREATE INDEX idx_logs_player_account ON logs_player (account);
CREATE INDEX idx_logs_player_guid ON logs_player (guid);
CREATE INDEX idx_logs_player_name ON logs_player (name);

CREATE TABLE logs_trade (
    time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    type TEXT NOT NULL DEFAULT '' CHECK (type IN (
        'AuctionBid', 'AuctionBuyout', 'BuyItem', 'SellItem', 'GM', 'Mail', 'QuestMaxLevel',
        'Quest', 'Loot', 'Trade', ''
    )),
    sender BIGINT NOT NULL DEFAULT 0 CHECK (sender >= 0),
    "senderType" BIGINT NOT NULL DEFAULT 0 CHECK ("senderType" >= 0),
    "senderEntry" BIGINT NOT NULL DEFAULT 0 CHECK ("senderEntry" >= 0),
    receiver BIGINT NOT NULL DEFAULT 0 CHECK (receiver >= 0),
    amount INTEGER NOT NULL DEFAULT 0,
    data INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX idx_logs_trade_sender ON logs_trade (sender);
CREATE INDEX idx_logs_trade_receiver ON logs_trade (receiver);

CREATE TABLE logs_transactions (
    time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    type TEXT CHECK (type IN ('Bid', 'Buyout', 'PlaceAuction', 'Trade', 'Mail', 'MailCOD')),
    guid1 BIGINT NOT NULL DEFAULT 0 CHECK (guid1 >= 0),
    money1 BIGINT NOT NULL DEFAULT 0 CHECK (money1 >= 0),
    spell1 BIGINT NOT NULL DEFAULT 0 CHECK (spell1 >= 0),
    items1 VARCHAR(255) NOT NULL DEFAULT '',
    guid2 BIGINT NOT NULL DEFAULT 0 CHECK (guid2 >= 0),
    money2 BIGINT NOT NULL DEFAULT 0 CHECK (money2 >= 0),
    spell2 BIGINT NOT NULL DEFAULT 0 CHECK (spell2 >= 0),
    items2 VARCHAR(255) NOT NULL DEFAULT ''
);

CREATE INDEX idx_logs_transactions_guid1 ON logs_transactions (guid1);
CREATE INDEX idx_logs_transactions_guid2 ON logs_transactions (guid2);

CREATE TABLE logs_trashcharacters (
    guid BIGINT PRIMARY KEY CHECK (guid >= 0),
    data VARCHAR(255) NOT NULL,
    cluster SMALLINT NOT NULL DEFAULT 0 CHECK (cluster >= 0)
);

CREATE TABLE smartlog_creature (
    time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    type TEXT NOT NULL DEFAULT '' CHECK (type IN ('Death', 'LongCombat', 'ScriptInfo', '')),
    entry INTEGER NOT NULL DEFAULT 0,
    guid INTEGER NOT NULL DEFAULT 0,
    specifier VARCHAR(255) NOT NULL DEFAULT '',
    "combatTime" INTEGER NOT NULL DEFAULT 0,
    content VARCHAR(255) NOT NULL DEFAULT ''
);

CREATE INDEX idx_smartlog_creature_entry ON smartlog_creature (entry);

CREATE TABLE system_fingerprint_usage (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fingerprint BIGINT NOT NULL CHECK (fingerprint >= 0),
    account BIGINT NOT NULL CHECK (account >= 0),
    ip VARCHAR(16) NOT NULL,
    realm BIGINT NOT NULL CHECK (realm >= 0),
    time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    architecture VARCHAR(16),
    cputype VARCHAR(64),
    activecpus BIGINT CHECK (activecpus >= 0),
    totalcpus BIGINT CHECK (totalcpus >= 0),
    pagesize BIGINT CHECK (pagesize >= 0)
);

CREATE INDEX idx_system_fingerprint_usage_fingerprint ON system_fingerprint_usage (fingerprint);
CREATE INDEX idx_system_fingerprint_usage_account ON system_fingerprint_usage (account);
CREATE INDEX idx_system_fingerprint_usage_ip ON system_fingerprint_usage (ip);

CREATE TABLE chat_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    channel_type VARCHAR(16) NOT NULL,
    channel_name VARCHAR(64),
    sender_guid BIGINT CHECK (sender_guid >= 0),
    sender_name VARCHAR(32),
    sender_account BIGINT CHECK (sender_account >= 0),
    target_guid BIGINT CHECK (target_guid >= 0),
    target_name VARCHAR(32),
    message VARCHAR(512) NOT NULL,
    map BIGINT CHECK (map >= 0),
    pos_x REAL,
    pos_y REAL,
    pos_z REAL
);

CREATE INDEX idx_chat_log_time ON chat_log (time);
CREATE INDEX idx_chat_log_sender ON chat_log (sender_guid);
CREATE INDEX idx_chat_log_sender_account ON chat_log (sender_account);
CREATE INDEX idx_chat_log_channel ON chat_log (channel_type, channel_name);
CREATE INDEX idx_chat_log_target ON chat_log (target_guid);
CREATE INDEX idx_chat_log_sender_time ON chat_log (sender_guid, time);

CREATE TABLE chat_outbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'sent', 'failed')),
    sender_account BIGINT NOT NULL CHECK (sender_account >= 0),
    sender_guid BIGINT NOT NULL CHECK (sender_guid >= 0),
    channel_type VARCHAR(16) NOT NULL DEFAULT 'Whisper',
    channel_name VARCHAR(64),
    target_guid BIGINT CHECK (target_guid >= 0),
    target_name VARCHAR(32),
    message VARCHAR(512) NOT NULL,
    processed_at TIMESTAMPTZ,
    error VARCHAR(255)
);

CREATE INDEX idx_chat_outbox_status ON chat_outbox (status);
