-- PostgreSQL migration: web / base_tables
-- Canonical PostgreSQL web schema.

CREATE TABLE web_sessions (
    token_hash BYTEA PRIMARY KEY CHECK (octet_length(token_hash) = 32),
    account_id BIGINT NOT NULL CHECK (account_id >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_seen_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX idx_web_sessions_account ON web_sessions (account_id);
CREATE INDEX idx_web_sessions_expiry ON web_sessions (expires_at);

CREATE TABLE web_identity_tokens (
    token_hash BYTEA PRIMARY KEY CHECK (octet_length(token_hash) = 32),
    account_id BIGINT NOT NULL CHECK (account_id >= 0),
    purpose TEXT NOT NULL CHECK (purpose IN ('email_verification', 'password_reset')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMPTZ NOT NULL,
    consumed_at TIMESTAMPTZ
);

CREATE INDEX idx_web_identity_tokens_account ON web_identity_tokens (account_id, purpose);
CREATE INDEX idx_web_identity_tokens_expiry ON web_identity_tokens (expires_at);

CREATE TABLE web_audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actor_account_id BIGINT CHECK (actor_account_id >= 0),
    action VARCHAR(96) NOT NULL,
    target_type VARCHAR(64) NOT NULL,
    target_id VARCHAR(128),
    reason VARCHAR(1024),
    request_id VARCHAR(36),
    remote_ip VARCHAR(45),
    details JSONB
);

CREATE INDEX idx_web_audit_actor_time ON web_audit_log (actor_account_id, occurred_at);
CREATE INDEX idx_web_audit_target_time ON web_audit_log (target_type, target_id, occurred_at);
CREATE INDEX idx_web_audit_action_time ON web_audit_log (action, occurred_at);

CREATE TABLE web_support_tickets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL CHECK (account_id >= 0),
    subject VARCHAR(160) NOT NULL,
    message TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'awaiting_player', 'resolved')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_web_support_tickets_account_updated ON web_support_tickets (account_id, updated_at);
CREATE INDEX idx_web_support_tickets_status_updated ON web_support_tickets (status, updated_at);

CREATE FUNCTION set_web_support_ticket_updated_at() RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER web_support_tickets_updated_at
BEFORE UPDATE ON web_support_tickets
FOR EACH ROW EXECUTE FUNCTION set_web_support_ticket_updated_at();
